language: python
python: "2.7"
env:
  - DATABASE_URL='postgres://travis:@127.0.0.1:5432/test'
services:
  - postgres
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test;' -U postgres
script: ./manage.py test test_pep8
